# Generated by Django 3.2.8 on 2021-11-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210921_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkanji',
            name='times_answered',
        ),
        migrations.RemoveField(
            model_name='userkanji',
            name='times_correct',
        ),
        migrations.AddField(
            model_name='userkanji',
            name='times_answered_english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userkanji',
            name='times_answered_kunyomi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userkanji',
            name='times_answered_onyomi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userkanji',
            name='times_correct_english',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userkanji',
            name='times_correct_kunyomi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userkanji',
            name='times_correct_onyomi',
            field=models.IntegerField(default=0),
        ),
    ]
